<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://com.cine" targetNamespace="http://com.cine">
	<wsdl:types>
		<xs:schema targetNamespace="http://com.cine" elementFormDefault="qualified">
			<xs:include schemaLocation="../Funciones/xsdfuncion.xsd"/> <!-- Rutas relativas-->
			<xs:include schemaLocation="../Funciones/commonsfuncion.xsd"/>
		</xs:schema>
	</wsdl:types>
	
	<wsdl:message name="movieFunctionRequest"> <!-- Petición para manejar elementos de tipo 'funcion'-->
		<wsdl:part name="parameter" element="tns:funcion"/>
	</wsdl:message>
	<wsdl:message name="ackResponse"> <!-- Creo que esto solo sirve como bandera al mandar peticiones-->
		<wsdl:part name="parameter" element="tns:ack"/>
	</wsdl:message>
	
	<wsdl:portType name="MovieFunctionPortType"> <!-- Las tres operaciones relacionadas con el elemento 'funcion'-->
		<wsdl:operation name="addMovieFunctionOperation">
			<wsdl:input message="tns:movieFunctionRequest"/>
			<wsdl:output message="tns:ackResponse"/>
		</wsdl:operation>
		<wsdl:operation name="deleteMovieFunctionOperation">
			<wsdl:input message="tns:movieFunctionRequest"/>
			<wsdl:output message="tns:ackResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="MovieFunctionBinding" type="tns:MovieFunctionPortType"> <!-- Esto creo que ejecuta las operaciones definidas-->
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="addMovieFunctionOperation">
			<soap:operation soapAction="urn:#NewOperation"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="deleteMovieFunctionOperation">
			<soap:operation soapAction="urn:#NewOperation"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="MovieFunctionService"> <!-- Servicio para manejar las peticiones de las funciones-->
		<wsdl:port name="MovieFunctionPort" binding="tns:MovieFunctionBinding">
			<soap:address location="No target address"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
